<a href="https://colab.research.google.com/github/SaydahbarovAzamjon-cloud/AI_Foundation/blob/main/nunpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install numpy

In [ ]:
import numpy as np

arr = np.array([1, 3, 5, 7])
print('numpy.array:', arr)

arr.shape

numpy.array: [1 3 5 7]


(4,)

In [ ]:
arr2 = np.array([[1,3,5,7], [4,6,8,9]])
print('numpy_array:', arr2)
arr2.shape

numpy_array: [[1 3 5 7]
 [4 6 8 9]]


(2, 4)

In [ ]:
#dtype => data type ni aniqlash uchun

a = np.array([1, 2, 3])
print(a.dtype)

int64


In [7]:
# reshape  => bu arrayning shape'ini o‘zgartiradi,
# elementlar soni esa o‘zgarmaydi.(1D => 2D ...)

a = np.array([1, 2, 3, 4, 5, 6])
b = a.reshape(2, 3)
print('shaped_array:', b)

shaped_array: [[1 2 3]
 [4 5 6]]


In [8]:
# astype() => bu typenozgartirib beradi
a = np.array([1, 2, 3])
b = a.astype(float)
print('float:', b)


float: [1. 2. 3.]


In [10]:
# np.zeros() -> berilgan shape'da 0 lardan iborat array yaratadi
# np.ones()  -> berilgan shape'da 1 lardan iborat array yaratadi
# Asosan: dummy data, test qilish va boshlang'ich qiymat berish uchun ishlatiladi.


z = np.zeros((2, 3))
o = np.ones((2, 3))

print("zeros:", z )
print("ones", o )

zeros: [[0. 0. 0.]
 [0. 0. 0.]]
ones [[1. 1. 1.]
 [1. 1. 1.]]


In [29]:
# ndim => array dimension ni aniqlab beradi

np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
]).ndim


3

In [31]:
# arrange bu berilgan qiymatni arange qiberadi (1, 7) => 1 ... 6

a = np.arange(1, 40)
print("a:", a)

a: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]


In [32]:
# sum() => array yegindisini beradi;
# mean()=> ortachasni oberadi
# min() => minimum
# max() => maximum

a = np.array([4, 5, 7, 9, 15])
print("sum:", a.sum())
print("mean:", a.mean())
print("min:", a.min())
print("max:", a.max())

sum: 40
mean: 8.0
min: 4
max: 15


In [36]:
# flatten => bu 2D yoki 3D arraylarni => 1D ga ozgartiradi

a = np.array([[1,2], [1,3]])
print(a.flatten())

[1 2 1 3]


In [40]:
# T (Transpose) => bu array element joyini almashtirib beradi

a = np.array([[1,5], [3,6]])
print("****", a.T)

**** [[1 3]
 [5 6]]


In [42]:
# dot(), @ => bu ikkita arayni bir biriga kopaytiradi

a  = np.array([[3,3], [3,5]])
b  = np.array([[3,3], [3,6]])
print('dot, multiplication', a.dot(b))

dot, multiplication [[18 27]
 [24 39]]


In [47]:
# random.rand() bu berilgan qiymatdan random array osil qilib beradi only float values 0.0..... ;

a = np.random.rand(2, 4)
print("randoms:", a)

randoms: [[0.22946083 0.42409856 0.23461715 0.82376153]
 [0.11077467 0.89179342 0.2670734  0.1685011 ]]
